@switch($viewInfo['key'])
    @case('equipment')
        @include('management.form.equipment')
        @break
    @case('report_type')
        @include('management.form.report_type')
        @break
    @case('machine_status')
        @include('management.form.machine_status')
        @break
    @case('user')
        @include('management.form.user')
        @break
    @case('product')
        @include('management.form.product')
        @break
    @case('report')
        @include('management.form.report')
        @break
    @case('machine')
        @include('management.form.machine')
        @break
@endswitch
